class Student < ActiveRecord::Base
  attr_accessible :ba_degree, 
  							  :ba_minor, 
  							  :birthdate,
  							  :city, 
  							  :combined_grade, 
  							  :coordinated_grade, 
  							  :curriculum, 
  							  :english_level, 
  							  :gender, 
  							  :group_description, 
  							  :id_number, 
  							  :institute, 
  							  :integrated_grade, 
  							  :mazat, 
  							  :mehina_grade, 
  							  :sat_grade, 
  							  :school, 
  							  :school_grade, 
  							  :semester, 
  							  :subject1_grade, 
  							  :subject2_grade, 
  							  :subject1_units, 
  							  :subject2_units, 
  							  :year, 
  							  :priority
end
